services:
  mongodb:
    container_name: blog-mongodb
    image: mongo:7.0
    # Redémarrer automatiquement
    restart: unless-stopped
    # Variable d'environnement
    environment:
      MONGO_INITDB_DATABASE: blog-mern
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    # Exposition du port
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/configdb
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

